Repository CS2103-AY1819S1-T16-2/main, pull requests merged in 2018-10, with the labels that each got.

#16 #8 Update profile picture and github link
  docs/AboutUs.adoc
  docs/images/triger15.png
  docs/images/yijinl.jpg
Labels: docs

#14 Feature user guide docs update
  .gitignore
  docs/UserGuide.adoc
Labels: docs

#18 View command implementation
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/student/SameStudentIdPredicate.java
  src/main/java/seedu/address/model/student/Student.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/student/SameStudentIdPredicateTest.java
Labels: core, enhancement

#21 [README.adoc] update project information
  README.adoc
Labels: docs

#23 #5 UI: change Ui from default app to SuperTA and include color scheme
  docs/images/ColorScheme.png
  docs/images/Ui.png
Labels: enhancement, ui

#25 #8 fix images of members from jpg to png format
  docs/AboutUs.adoc
  docs/images/caephler.png
  docs/images/darieca.png
  docs/images/wenshei.png
Labels: bug, docs

#33 Update Developer Guide with Introduction
  docs/DeveloperGuide.adoc
Labels: docs

#34 Remove unnecessary parts from Developer Guide
  docs/DeveloperGuide.adoc
Labels: docs

#35 Remove Coming in v1.* from User Guide
  docs/UserGuide.adoc
Labels: docs

#49 Add user stories into Developer Guide
  docs/DeveloperGuide.adoc
Labels: docs, type.Story

#60 Changed Grade type to Double
  src/main/java/seedu/superta/logic/parser/CreateAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/ParserUtil.java
  src/main/java/seedu/superta/model/assignment/Assignment.java
  src/main/java/seedu/superta/model/assignment/Grade.java
  src/main/java/seedu/superta/model/assignment/GradeBook.java
  src/main/java/seedu/superta/storage/XmlAdaptedAssignment.java
  src/main/java/seedu/superta/storage/XmlGrade.java
Labels: enhancement

#61 Edit developer guide
  docs/DeveloperGuide.adoc
Labels: docs

#71 Changes to Assignment
  src/main/java/seedu/superta/logic/parser/CliSyntax.java
  src/main/java/seedu/superta/logic/parser/CreateAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/ParserUtil.java
  src/main/java/seedu/superta/model/assignment/Assignment.java
  src/main/java/seedu/superta/model/assignment/AssignmentList.java
  src/main/java/seedu/superta/model/assignment/Grade.java
  src/main/java/seedu/superta/model/assignment/Title.java
  src/main/java/seedu/superta/model/assignment/UniqueAssignmentList.java
  src/main/java/seedu/superta/model/assignment/exceptions/DuplicateAssignmentException.java
  src/main/java/seedu/superta/model/tutorialgroup/TutorialGroup.java
  src/main/java/seedu/superta/storage/XmlAdaptedAssignment.java
  src/main/java/seedu/superta/storage/XmlAdaptedTutorialGroup.java
  src/test/java/seedu/superta/model/ModelManagerTest.java
  src/test/java/seedu/superta/model/SuperTaClientTest.java
  src/test/java/seedu/superta/model/assignment/TitleTest.java
  src/test/java/seedu/superta/testutil/TutorialGroupBuilder.java
Labels: core

#75 Remove address class and related fields/methods
  docs/UserGuide.adoc
  src/main/java/seedu/superta/logic/commands/AddCommand.java
  src/main/java/seedu/superta/logic/commands/EditCommand.java
  src/main/java/seedu/superta/logic/parser/AddCommandParser.java
  src/main/java/seedu/superta/logic/parser/CliSyntax.java
  src/main/java/seedu/superta/logic/parser/EditCommandParser.java
  src/main/java/seedu/superta/logic/parser/ParserUtil.java
  src/main/java/seedu/superta/model/SuperTaClient.java
  src/main/java/seedu/superta/model/student/Address.java
  src/main/java/seedu/superta/model/student/Student.java
  src/main/java/seedu/superta/model/util/SampleDataUtil.java
  src/main/java/seedu/superta/storage/XmlAdaptedStudent.java
  src/main/java/seedu/superta/ui/StudentCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlSerializableSuperTaClientTest/typicalPersonsAddressBook.xml
  src/test/data/XmlSuperTaClientStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/superta/commons/util/XmlUtilTest.java
  src/test/java/seedu/superta/logic/commands/CommandTestUtil.java
  src/test/java/seedu/superta/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/superta/logic/commands/ViewStudentFeedbackCommandTest.java
  src/test/java/seedu/superta/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/superta/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/superta/logic/parser/ParserUtilTest.java
  src/test/java/seedu/superta/model/SuperTaClientTest.java
  src/test/java/seedu/superta/model/student/AddressTest.java
  src/test/java/seedu/superta/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/superta/model/student/SameStudentIdPredicateTest.java
  src/test/java/seedu/superta/model/student/StudentTest.java
  src/test/java/seedu/superta/model/student/UniqueStudentListTest.java
  src/test/java/seedu/superta/storage/XmlAdaptedStudentTest.java
  src/test/java/seedu/superta/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/superta/testutil/StudentBuilder.java
  src/test/java/seedu/superta/testutil/StudentUtil.java
  src/test/java/seedu/superta/testutil/TypicalStudents.java
  src/test/java/seedu/superta/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: core, type.Task

#87 Assignment tests
  src/main/java/seedu/superta/logic/commands/CreateAssignmentCommand.java
  src/main/java/seedu/superta/logic/commands/GradeAssignmentCommand.java
  src/main/java/seedu/superta/logic/parser/CreateAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/GradeAssignmentCommandParser.java
  src/main/java/seedu/superta/logic/parser/ParserUtil.java
  src/main/java/seedu/superta/model/SuperTaClient.java
  src/main/java/seedu/superta/model/assignment/Assignment.java
  src/main/java/seedu/superta/model/assignment/GradeBook.java
  src/main/java/seedu/superta/model/assignment/exceptions/GradeException.java
  src/test/java/seedu/superta/logic/commands/CommandTestUtil.java
  src/test/java/seedu/superta/logic/commands/CreateAssignmentCommandTest.java
  src/test/java/seedu/superta/model/assignment/AssignmentTest.java
  src/test/java/seedu/superta/model/assignment/TitleTest.java
  src/test/java/seedu/superta/model/assignment/UniqueAssignmentListTest.java
  src/test/java/seedu/superta/testutil/AssignmentBuilder.java
  src/test/java/seedu/superta/testutil/TypicalAssignments.java
Labels: status.Ongoing, tests

#88 Change color scheme of UI
  .gitignore
  config.json
  docs/images/ColorScheme.png
  src/main/resources/images/address_book_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: enhancement, ui

#90 Added RemoveStudentFromTutorialGroupCommand
  src/main/java/seedu/superta/logic/commands/CreateAssignmentCommand.java
  src/main/java/seedu/superta/logic/commands/RemoveStudentFromTutorialGroupCommand.java
  src/main/java/seedu/superta/logic/parser/RemoveStudentFromTutorialGroupCommandParser.java
  src/main/java/seedu/superta/logic/parser/SuperTaClientParser.java
  src/main/java/seedu/superta/model/Model.java
  src/main/java/seedu/superta/model/ModelManager.java
  src/main/java/seedu/superta/model/SuperTaClient.java
  src/test/java/seedu/superta/logic/commands/AddCommandTest.java
  src/test/java/seedu/superta/logic/commands/AddStudentToTutorialGroupCommandTest.java
  src/test/java/seedu/superta/logic/commands/CreateAssignmentCommandTest.java
  src/test/java/seedu/superta/logic/commands/RemoveStudentFromTutorialGroupCommandTest.java
Labels: core, enhancement

#97 Create and mark attendance commands
  docs/UserGuide.adoc
  docs/team/yuheong.adoc
  src/main/java/seedu/superta/logic/commands/CreateAttendanceCommand.java
  src/main/java/seedu/superta/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/superta/logic/parser/CliSyntax.java
  src/main/java/seedu/superta/logic/parser/CreateAttendanceCommandParser.java
  src/main/java/seedu/superta/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/superta/logic/parser/ParserUtil.java
  src/main/java/seedu/superta/logic/parser/SuperTaClientParser.java
  src/main/java/seedu/superta/model/Model.java
  src/main/java/seedu/superta/model/ModelManager.java
  src/main/java/seedu/superta/model/SuperTaClient.java
  src/main/java/seedu/superta/model/attendance/Attendance.java
  src/main/java/seedu/superta/model/attendance/Presence.java
  src/main/java/seedu/superta/model/attendance/Session.java
  src/main/java/seedu/superta/model/attendance/UniqueSessionList.java
  src/main/java/seedu/superta/model/attendance/exceptions/DuplicateAttendanceException.java
  src/main/java/seedu/superta/model/attendance/exceptions/DuplicateSessionException.java
  src/main/java/seedu/superta/model/attendance/exceptions/SessionNotFoundException.java
  src/main/java/seedu/superta/model/student/Student.java
  src/main/java/seedu/superta/model/student/UniqueStudentList.java
  src/main/java/seedu/superta/model/tutorialgroup/TutorialGroup.java
  src/main/java/seedu/superta/storage/XmlAdaptedAttendance.java
  src/main/java/seedu/superta/storage/XmlAdaptedSession.java
  src/main/java/seedu/superta/storage/XmlAdaptedTutorialGroup.java
  src/test/java/seedu/superta/logic/commands/AddCommandTest.java
  src/test/java/seedu/superta/logic/commands/CreateAssignmentCommandTest.java
  src/test/java/seedu/superta/logic/parser/SuperTaClientParserTest.java
  src/test/java/seedu/superta/testutil/TutorialGroupBuilder.java
Labels: core, enhancement, priority.Medium, status.Ongoing, type.Enhancement
